name: Render PEPs

on: [push, pull_request, workflow_dispatch]

jobs:
  render-peps:
    name: Render PEPs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.x", "3.11-dev"]

    steps:
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history so that last modified date-times are accurate

      - name: ðŸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: ðŸ‘·â€ Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: ðŸ”§ Render PEPs
        run: make pages JOBS=$(nproc)

        # remove the .doctrees folder when building for deployment as it takes two thirds of disk space
      - name: ðŸ”¥ Clean up files
        run: rm -r build/.doctrees/

      - name: Add CNAME
        run: echo "peps.nogil.dev" > build/CNAME

      - name: ðŸš€ Deploy to GitHub pages
        # This allows CI to build branches for testing
        if: (github.ref == 'refs/heads/nogil-drafts') && (matrix.python-version == '3.x')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # Synchronise with build.py -> build_directory
          single-commit: true # Delete existing files
